### ISSUE TITLE
Add config setting to specify folders containing rego

### ISSUE THREAD

**Issue by teq0** [tsandall/vscode-opa#12]
Currently opa is passed the workspace root as the path. This means that anything that opa doesn't understand, such as Kubernetes YAML files, show up as problems in the workspace, which is particularly annoying when it checks every time you save a file.

I propose adding a section to the config to specify one or more folders where rego is stored, creating a method that returns the list of rego folders, say `getRegoPaths()`, and replacing all references to 

```let rootPath = vscode.workspace.workspaceFolders![0].uri.fsPath;```

with 

```let regoPaths = getRegoPaths()```

Or something similar. The alternative would be to specify folders to ignore, but that would mean creating the list of paths dynamically every time a command is run, since the actual list of folders could change at any time.

It's not exactly locking it down to evaluating a specific package, but it would help when you have rego policies in the same project as other code.

**Comment by tsandall** [comment]
@teq0 thanks for filing this!

This issue has come up in the past in a different place: when you use any of the subcommands like `opa test` or `opa run` or ... it'll try to load all of the files contained in specified directories, recursively. While this works fine in dirs/repos/workspaces that are "pure", it falls over in the more common case.

One idea I've been kicking around is to add support for an `.opaignore` file. Here's the ticket I filed: https://github.com/open-policy-agent/opa/issues/1087

WDYT of that solution? Personally, I'd rather solve it at the file loading layer because that'll work for command line usage, VS Code usage, as well as other integrations in the future (e.g., IntelliJ)

**Comment by teq0** [comment]
I'm happy to have a go at it if you agree with the idea.

Actually --ignore seems to be common to all commands, might be simpler to specify the --ignore parameters.

**Comment by teq0** [comment]
That's sounds like a better idea. Happy to have a go at adding that instead.

**Comment by tsandall** [comment]
Perfect. We can close this issue once the changes are merged into OPA.

**Comment by morgante** [comment]
@tsandall I think the .opaignore file is a nice addition but I still think we should have some way of ignoring this in the extension itself.

Context: I work on a large project which contains many different components. Only one small subcomponent includes OPA so adding an .opaignore high in the hierarchy would be an unwelcome change. Fundamentally I only want the OPA extension to invoke on a very specific subdirectory.

**Comment by teq0** [comment]
Actually I've finally started making some progress on https://github.com/open-policy-agent/opa/issues/1087 and I've realised that it's not clear where it should look for the .opaignore file. But I'll comment over there.

**Comment by tsandall** [comment]
@morgante that's reasonable. I don't think these solutions are mutually exclusive. Since the .opaignore solution is widely applicable, I'd still like that to be the preferred approach.

In cases where users are VS Code in a large monorepo workspace and don't have permission to add an .opaignore file at the root or update the VCS's ignore file, the VS Code specific configuration would be nice to have. If you'd like to put a PR together, feel free.

**Comment by tsandall** [comment]
This should be taken care of in v0.4.2 of the extension. @morgante hope this helps out!
