### ISSUE TITLE
Evaluate Selection Not Working

### ISSUE THREAD

**Issue by 425devon** [tsandall/vscode-opa#13]
Evaluate Selection is not functioning. I cloned the repo from Kubecon 2018 and tried to follow the [demonstration](https://youtu.be/Vdy26oA3py8?t=747)

* All rules are returning default of false
* Unable to evaluate attributes i.e 
Selecting:
`input.method = "GET"` 
with input.json:
```json
{
    "method": "GET",
    "path": [
        "accounts",
        "bob"
    ],
    "subject": {
        "user": "bob"
    }
}
```
Evaluate selection returns:
output.json
`//No results found`

_Small side note the test.rego is working fine_

OS: macOS High Sierra version 10.13.6
VS Code Version Version 1.30.2 (1.30.2)

**Comment by tsandall** [comment]
Hrmmm. The only thing I can think of that could be going wrong is that you have your VS Code opened in the root of the demo repository. You'll need to make sure you open it in the hands-on dir since that's where the input.json file is located. You could confirm this by selecting something trivial like "GET" and evaluating that.

**Comment by 425devon** [comment]
You are absolutely correct, I was in the root directory. After moving to the directory containing the .rego and input.json everything is working as expected. 
I appreciate the quick response! This was driving me nuts.
