### ISSUE TITLE
Can't install REPL

### ISSUE THREAD

**Issue by yordis** [tsandall/vscode-opa#15]
I installed the extension and I keep getting this issue.

```
Getting latest OPA release for your platform...
Found latest OPA release: https://github.com/open-policy-agent/opa/releases/download/v0.10.7/opa_darwin_amd64
Downloading OPA executable...
Something went wrong while downloading the OPA executable:
TypeError: Cannot read property 'startsWith' of undefined
```

OS: MacOS
VSCode: `Version 1.33.1 (1.33.1)`

**Comment by tsandall** [comment]
@yordis I'm not sure what's happening here. It looks like the opa executable download failed and then inside the error handling path, `startsWith` was called and the extension threw a TypeError.

However, the extension itself never calls `startsWith` so I think that error is coming from inside vscode or perhaps the extension, i.e., not vscode-opa itself. As such, there's not much that I can do about it.

FWIW, all this step does is download the latest OPA executable and then configure vscode to use it. You can set the config yourself (`opa.path`) if you download the executable manually.

Closing this issue because I don't think there's anything to be done for now.

**Comment by devorbitus** [comment]
I am pretty sure https://github.com/tsandall/vscode-opa/pull/22 fixes this
